#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# base-tools.sh - standard tools and shell comfort on a fresh server
# Packages (nano, vim, screen, ...) plus system-wide defaults for shell
# colours, editors and screen.
# Modes: (no argument) = interactive menu
#        --status      = short status on stdout
#        --uninstall   = uninstall
set -euo pipefail

# --version must come before the root check so it answers without sudo.
# if-form instead of "[[ ]] &&": a false && would exit under set -e.
VERSION="2.2.0"
if [[ "${1:-}" == "--version" ]]; then echo "$(basename "$0") $VERSION"; exit 0; fi

[[ $EUID -ne 0 ]] && { echo "Please run as root (sudo)." >&2; exit 1; }

PROFILE_D=/etc/profile.d/zz-base-tools.sh
BASHRC=/etc/bash.bashrc
NANORC=/etc/nanorc
SCREENRC=/etc/screenrc
VIMRC=/etc/vim/vimrc.local

MARK_BEGIN='# >>> base-tools >>>'
MARK_END='# <<< base-tools <<<'

# Nothing useful happens on a server without these - they are installed
# without asking.
PKGS_ALWAYS=(git ca-certificates)

PKGS_EDITOR=(nano vim)
PKGS_SESSION=(screen tmux)
PKGS_TOOLS=(htop curl wget unzip rsync tree ncdu bash-completion)
PKGS_NET=(dnsutils net-tools mtr-tiny)

pause() { read -rp "Press Enter to continue..." _; }

# confirm "Question" [Y]   -> default Y instead of N
confirm() {
    local q=$1 def=${2:-N} ans
    if [[ "$def" == "Y" ]]; then
        read -rp "$q [Y/n]: " ans; ans=${ans:-Y}
    else
        read -rp "$q [y/N]: " ans; ans=${ans:-N}
    fi
    [[ "$ans" =~ ^[YyJj]$ ]]
}

# make_backup <name> <path>...   -> /root/<name>-uninstall-<ts>.tar.gz
make_backup() {
    local name=$1; shift
    local ts tgz p
    local -a existing=()
    for p in "$@"; do [[ -e "$p" ]] && existing+=("$p"); done
    if (( ${#existing[@]} == 0 )); then
        echo "(nothing to back up)"
        return 0
    fi
    mkdir -p /root 2>/dev/null || true
    ts=$(date +%Y%m%d-%H%M%S)
    tgz="/root/${name}-uninstall-${ts}.tar.gz"
    if tar czf "$tgz" --absolute-names "${existing[@]}"; then
        chmod 600 "$tgz"
        echo "Backup: $tgz"
    else
        echo "!!! Backup failed - aborting, nothing is removed." >&2
        return 1
    fi
}

# ---------------------------------------------------------------------------
# Marked blocks in files owned by someone else
# ---------------------------------------------------------------------------
has_block() { grep -qF "$MARK_BEGIN" "$1" 2>/dev/null; }

remove_block() {
    local f=$1
    [[ -f "$f" ]] || return 0
    has_block "$f" || return 0
    sed -i "\|^${MARK_BEGIN}\$|,\|^${MARK_END}\$|d" "$f"
}

# write_block <file>   - content comes from stdin
write_block() {
    local f=$1
    remove_block "$f"
    [[ -f "$f" ]] || touch "$f"
    { echo "$MARK_BEGIN"; cat; echo "$MARK_END"; } >> "$f"
}

is_setup() { [[ -f "$PROFILE_D" ]]; }

# ---------------------------------------------------------------------------
# Packages
# ---------------------------------------------------------------------------
install_group() {
    local label=$1; shift
    local -a pkgs=("$@")
    local p
    echo
    echo "--- ${label}: ${pkgs[*]}"
    for p in "${pkgs[@]}"; do
        if dpkg -s "$p" &>/dev/null; then
            echo "    $p (already installed)"
        elif DEBIAN_FRONTEND=noninteractive apt-get install -y "$p" >/dev/null 2>&1; then
            echo "    $p installed"
        else
            echo "    !!! $p could not be installed (package name unknown on this distribution?)"
        fi
    done
}

install_packages() {
    echo ">>> Package selection"
    echo
    echo "Always installed: ${PKGS_ALWAYS[*]}"
    echo
    local do_editor=0 do_session=0 do_tools=0 do_net=0
    if confirm "Editors (${PKGS_EDITOR[*]})?"             Y; then do_editor=1;  fi
    if confirm "Terminal sessions (${PKGS_SESSION[*]})?"  Y; then do_session=1; fi
    if confirm "Tools (${PKGS_TOOLS[*]})?"                Y; then do_tools=1;   fi
    if confirm "Network diagnostics (${PKGS_NET[*]})?"    N; then do_net=1;     fi

    echo
    echo ">>> Updating package lists..."
    apt-get update -qq || true

    install_group "Base (always)" "${PKGS_ALWAYS[@]}"

    (( do_editor  == 1 )) && install_group "Editors"             "${PKGS_EDITOR[@]}"  || true
    (( do_session == 1 )) && install_group "Terminal sessions"   "${PKGS_SESSION[@]}" || true
    (( do_tools   == 1 )) && install_group "Tools"               "${PKGS_TOOLS[@]}"   || true
    (( do_net     == 1 )) && install_group "Network diagnostics" "${PKGS_NET[@]}"     || true

    echo
    echo ">>> Packages done."
}

# ---------------------------------------------------------------------------
# Shell, editor and screen defaults
# ---------------------------------------------------------------------------
write_shell_config() {
    # Our own file, no foreign content - it is overwritten completely.
    cat > "$PROFILE_D" <<'EOF'
# Coloured shell and comfort - generated by base-tools.sh
# Loaded by login shells (/etc/profile) and, via /etc/bash.bashrc, by
# interactive non-login shells as well.

case $- in *i*) ;; *) return 0 ;; esac
[ -z "${BASH_VERSION:-}" ] && return 0

if command -v dircolors >/dev/null 2>&1; then
    if [ -r "$HOME/.dircolors" ]; then
        eval "$(dircolors -b "$HOME/.dircolors")"
    else
        eval "$(dircolors -b)"
    fi
fi

alias ls='ls --color=auto'
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias df='df -h'
alias du='du -h'
alias ..='cd ..'

export LESS='-R'
export HISTSIZE=5000
export HISTFILESIZE=10000
export HISTCONTROL=ignoreboth
export HISTTIMEFORMAT='%F %T  '
shopt -s histappend checkwinsize 2>/dev/null

# Prompt: root red, normal user green, path blue
if [ "$(id -u)" -eq 0 ]; then
    PS1='\[\e[1;31m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]# '
else
    PS1='\[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]$ '
fi
EOF
    chmod 644 "$PROFILE_D"

    # /etc/profile.d is only read by login shells. So that 'ssh host cmd',
    # 'su' and screen get the same settings, pull it in here as well.
    write_block "$BASHRC" <<EOF
[ -r ${PROFILE_D} ] && . ${PROFILE_D}
EOF
    echo "    ${PROFILE_D} written, ${BASHRC} points at it"
}

write_vim_config() {
    mkdir -p "$(dirname "$VIMRC")"
    if [[ -f "$VIMRC" ]] && ! head -1 "$VIMRC" | grep -q 'base-tools'; then
        cp "$VIMRC" "$VIMRC.orig"
        echo "    existing $VIMRC backed up to $VIMRC.orig"
    fi
    cat > "$VIMRC" <<'EOF'
" generated by base-tools.sh
syntax on
set number
set ruler
set hlsearch
set incsearch
set ignorecase
set smartcase
set tabstop=4
set shiftwidth=4
set expandtab
set background=dark
set encoding=utf-8
" Mouse off: otherwise vim switches to visual mode on selection and copying
" out of the terminal stops working.
set mouse=
EOF
    chmod 644 "$VIMRC"
    echo "    $VIMRC written"
}

write_nano_config() {
    local inc=""
    [[ -d /usr/share/nano ]] && inc='include "/usr/share/nano/*.nanorc"' || true
    write_block "$NANORC" <<EOF
set linenumbers
set tabsize 4
set tabstospaces
set constantshow
set softwrap
${inc}
EOF
    echo "    block placed in $NANORC"
}

write_screen_config() {
    write_block "$SCREENRC" <<'EOF'
startup_message off
defscrollback 10000
altscreen on
hardstatus alwayslastline "%{= kG}[%H]%{= kw} %-w%{= KW}%n %t%{-}%+w %=%{= kG}%c  %Y-%m-%d"
EOF
    echo "    block placed in $SCREENRC"
}

write_configs() {
    echo ">>> Defaults"
    write_shell_config
    write_vim_config
    write_nano_config
    write_screen_config
    echo
    echo "In effect in every new session. For the current shell:"
    echo "    . ${PROFILE_D}"
}

setup_all() {
    install_packages
    echo
    write_configs
    echo
    pause
}

# ---------------------------------------------------------------------------
# Status
# ---------------------------------------------------------------------------
pkg_state() {
    local p
    for p in "$@"; do
        if dpkg -s "$p" &>/dev/null; then
            printf '  [x] %s\n' "$p"
        else
            printf '  [ ] %s\n' "$p"
        fi
    done
}

show_status() {
    echo "--- Packages ---"
    pkg_state "${PKGS_ALWAYS[@]}" "${PKGS_EDITOR[@]}" "${PKGS_SESSION[@]}" \
              "${PKGS_TOOLS[@]}" "${PKGS_NET[@]}"
    echo
    echo "--- Defaults ---"
    printf '  [%s] %s\n' "$([[ -f "$PROFILE_D" ]] && echo x || echo ' ')" "$PROFILE_D"
    printf '  [%s] %s (points at the shell configuration)\n' "$(has_block "$BASHRC" && echo x || echo ' ')" "$BASHRC"
    printf '  [%s] %s\n' "$([[ -f "$VIMRC" ]] && echo x || echo ' ')" "$VIMRC"
    printf '  [%s] %s\n' "$(has_block "$NANORC" && echo x || echo ' ')" "$NANORC"
    printf '  [%s] %s\n' "$(has_block "$SCREENRC" && echo x || echo ' ')" "$SCREENRC"
}

# ---------------------------------------------------------------------------
# Uninstall
# ---------------------------------------------------------------------------
uninstall() {
    echo ">>> Uninstall base-tools"
    echo
    # A hand-written vimrc.local that did not come from here stays untouched.
    local vim_ours=0 vimnote=""
    if [[ -f "$VIMRC.orig" ]]; then
        vim_ours=1; vimnote=" (the previous version is restored)"
    elif [[ -f "$VIMRC" ]] && head -1 "$VIMRC" | grep -q 'base-tools'; then
        vim_ours=1
    fi

    echo "The following will be removed:"
    [[ -f "$PROFILE_D" ]] && echo "  - $PROFILE_D"                  || true
    has_block "$BASHRC"   && echo "  - marked block in $BASHRC"     || true
    (( vim_ours == 1 ))   && echo "  - ${VIMRC}${vimnote}"          || true
    has_block "$NANORC"   && echo "  - marked block in $NANORC"     || true
    has_block "$SCREENRC" && echo "  - marked block in $SCREENRC"   || true
    echo
    echo "The installed packages stay - taking nano and vim away from a server"
    echo "does more damage than it cleans up. If you want them gone anyway:"
    echo "    apt purge ${PKGS_EDITOR[*]} ${PKGS_SESSION[*]} ${PKGS_TOOLS[*]} ${PKGS_NET[*]}"
    echo "  (git and ca-certificates are deliberately not on that line)"
    echo

    confirm "Really remove?" || { echo "Cancelled."; pause; return; }

    make_backup base-tools "$PROFILE_D" "$BASHRC" "$VIMRC" "$NANORC" "$SCREENRC" || { pause; return; }

    rm -f "$PROFILE_D"
    remove_block "$BASHRC"
    # nanorc and screenrc may not have existed before - then an empty file is
    # left behind after removing the block, and that can go too.
    remove_block "$NANORC";   [[ -s "$NANORC" ]]   || rm -f "$NANORC"
    remove_block "$SCREENRC"; [[ -s "$SCREENRC" ]] || rm -f "$SCREENRC"

    if [[ -f "$VIMRC.orig" ]]; then
        mv "$VIMRC.orig" "$VIMRC"
        echo "$VIMRC restored from $VIMRC.orig."
    elif (( vim_ours == 1 )); then
        rm -f "$VIMRC"
    fi

    echo
    echo "Removed. New sessions get the default shell again."
    pause
}

# ---------------------------------------------------------------------------
# Menu
# ---------------------------------------------------------------------------
main_menu() {
    while true; do
        clear
        echo "==========================================="
        echo " Base tools and shell comfort"
        echo "==========================================="
        if is_setup; then
            echo "Status: set up"
        else
            echo "Status: not set up"
        fi
        echo
        echo "1) Set up everything (packages + defaults)"
        echo "2) Install packages only"
        echo "3) Write defaults only (shell, vim, nano, screen)"
        echo "4) Show status"
        echo "5) Uninstall"
        echo "6) Quit"
        read -rp "Choice: " CH
        case "$CH" in
            1) setup_all ;;
            2) install_packages; pause ;;
            3) write_configs; pause ;;
            4) show_status; pause ;;
            5) uninstall ;;
            6) exit 0 ;;
            *) sleep 1 ;;
        esac
    done
}

case "${1:-}" in
    --status)    show_status ;;
    --uninstall) uninstall ;;
    "")          main_menu ;;
    *)           echo "Usage: $0 [--status|--uninstall|--version]"; exit 1 ;;
esac
