#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# mail-setup.sh - set up SMTP sending (msmtp as a sendmail replacement)
# No entity management, only parameter configuration.
set -euo pipefail

# --version must come before the root check so it answers without sudo.
# if-form instead of "[[ ]] &&": a false && would exit under set -e.
VERSION="2.0.0"
if [[ "${1:-}" == "--version" ]]; then echo "$(basename "$0") $VERSION"; exit 0; fi

[[ $EUID -ne 0 ]] && { echo "Please run as root (sudo)." >&2; exit 1; }

MSMTPRC=/etc/msmtprc
ALIASES=/etc/aliases
LOGFILE=/var/log/msmtp.log

pause() { read -rp "Press Enter to continue..." _; }

# confirm "Question" [Y]   -> default Y instead of N
confirm() {
    local q=$1 def=${2:-N} ans
    if [[ "$def" == "Y" ]]; then
        read -rp "$q [Y/n]: " ans; ans=${ans:-Y}
    else
        read -rp "$q [y/N]: " ans; ans=${ans:-N}
    fi
    [[ "$ans" =~ ^[YyJj]$ ]]
}

# make_backup <name> <path>...   -> /root/<name>-uninstall-<ts>.tar.gz
make_backup() {
    local name=$1; shift
    local ts tgz p
    local -a existing=()
    for p in "$@"; do [[ -e "$p" ]] && existing+=("$p"); done
    if (( ${#existing[@]} == 0 )); then
        echo "(nothing to back up)"
        return 0
    fi
    mkdir -p /root 2>/dev/null || true
    ts=$(date +%Y%m%d-%H%M%S)
    tgz="/root/${name}-uninstall-${ts}.tar.gz"
    if tar czf "$tgz" --absolute-names "${existing[@]}"; then
        chmod 600 "$tgz"
        echo "Backup: $tgz"
    else
        echo "!!! Backup failed - aborting, nothing is removed." >&2
        return 1
    fi
}

is_setup() { [[ -f "$MSMTPRC" ]] && grep -q '^account ' "$MSMTPRC"; }

get_val() { grep -m1 "^${1} " "$MSMTPRC" 2>/dev/null | awk '{print $2}' || true; }

install_pkgs() {
    if ! command -v msmtp &>/dev/null; then
        echo ">>> Installing msmtp, msmtp-mta, bsd-mailx..."
        apt update -qq
        DEBIAN_FRONTEND=noninteractive apt install -y msmtp msmtp-mta bsd-mailx >/dev/null
    fi
    if ! command -v mail &>/dev/null; then
        DEBIAN_FRONTEND=noninteractive apt install -y bsd-mailx >/dev/null
    fi
}

configure() {
    install_pkgs

    local cur_host cur_port cur_user cur_from cur_tls cur_starttls cur_rcpt
    if is_setup; then
        cur_host=$(get_val host)
        cur_port=$(get_val port)
        cur_user=$(get_val user)
        cur_from=$(get_val from)
        cur_tls=$(get_val tls)
        cur_starttls=$(get_val tls_starttls)
        cur_rcpt=$(awk '/^root:/ {print $2}' "$ALIASES" 2>/dev/null || true)
    fi

    echo "--- SMTP parameters ---"
    read -rp "SMTP server [${cur_host:-}]: " SMTP_HOST
    SMTP_HOST=${SMTP_HOST:-${cur_host:-}}
    while [[ -z "$SMTP_HOST" ]]; do read -rp "  -> required: " SMTP_HOST; done

    echo
    echo "Encryption:"
    echo "  1) STARTTLS  (port 587, the usual one)"
    echo "  2) TLS/SSL   (port 465, implicit)"
    echo "  3) unencrypted (port 25, internal network only)"
    read -rp "Choice [1]: " ENC; ENC=${ENC:-1}

    local DEF_PORT TLS_ON STARTTLS_ON
    case "$ENC" in
        2) DEF_PORT=465; TLS_ON=on;  STARTTLS_ON=off ;;
        3) DEF_PORT=25;  TLS_ON=off; STARTTLS_ON=off ;;
        *) DEF_PORT=587; TLS_ON=on;  STARTTLS_ON=on  ;;
    esac

    read -rp "Port [${cur_port:-$DEF_PORT}]: " SMTP_PORT
    SMTP_PORT=${SMTP_PORT:-${cur_port:-$DEF_PORT}}

    read -rp "Authentication needed? [Y/n]: " NEEDAUTH
    NEEDAUTH=${NEEDAUTH:-Y}

    local SMTP_USER="" SMTP_PASS=""
    if [[ "$NEEDAUTH" =~ ^[YyJj]$ ]]; then
        read -rp "Username [${cur_user:-}]: " SMTP_USER
        SMTP_USER=${SMTP_USER:-${cur_user:-}}
        while [[ -z "$SMTP_USER" ]]; do read -rp "  -> required: " SMTP_USER; done

        read -rsp "Password (empty = keep the existing one): " SMTP_PASS; echo
        if [[ -z "$SMTP_PASS" ]] && is_setup; then
            SMTP_PASS=$(grep -m1 '^password ' "$MSMTPRC" | cut -d' ' -f2- || true)
        fi
        while [[ -z "$SMTP_PASS" ]]; do
            read -rsp "  -> required: " SMTP_PASS; echo
        done
    fi

    read -rp "Sender address (From) [${cur_from:-}]: " MAIL_FROM
    MAIL_FROM=${MAIL_FROM:-${cur_from:-}}
    while [[ -z "$MAIL_FROM" ]]; do read -rp "  -> required: " MAIL_FROM; done

    read -rp "Default recipient for system/root mail [${cur_rcpt:-}]: " ROOT_RCPT
    ROOT_RCPT=${ROOT_RCPT:-${cur_rcpt:-}}

    read -rp "Check the server certificate? [Y/n]: " CERTCHECK
    CERTCHECK=${CERTCHECK:-Y}

    umask 077
    {
        echo "# msmtp - generated by mail-setup.sh on $(date '+%F %T')"
        echo "defaults"
        echo "auth           $([[ "$NEEDAUTH" =~ ^[YyJj]$ ]] && echo on || echo off)"
        echo "tls            ${TLS_ON}"
        echo "tls_starttls   ${STARTTLS_ON}"
        if [[ "$CERTCHECK" =~ ^[YyJj]$ ]]; then
            echo "tls_trust_file /etc/ssl/certs/ca-certificates.crt"
        else
            echo "tls_certcheck  off"
        fi
        echo "logfile        ${LOGFILE}"
        echo "timeout        20"
        echo
        echo "account        default"
        echo "host           ${SMTP_HOST}"
        echo "port           ${SMTP_PORT}"
        echo "from           ${MAIL_FROM}"
        if [[ "$NEEDAUTH" =~ ^[YyJj]$ ]]; then
            echo "user           ${SMTP_USER}"
            echo "password       ${SMTP_PASS}"
        fi
    } > "$MSMTPRC"

    chmod 600 "$MSMTPRC"
    chown root:root "$MSMTPRC"
    touch "$LOGFILE" && chmod 600 "$LOGFILE"

    if [[ -n "$ROOT_RCPT" ]]; then
        touch "$ALIASES"
        if grep -q '^root:' "$ALIASES"; then
            sed -i "s|^root:.*|root: ${ROOT_RCPT}|" "$ALIASES"
        else
            echo "root: ${ROOT_RCPT}" >> "$ALIASES"
        fi
        command -v newaliases &>/dev/null && newaliases 2>/dev/null || true
    fi

    echo
    echo "Configuration written to $MSMTPRC (chmod 600)."
    echo "Careful: the password sits there in clear text, readable only by root."
    echo

    read -rp "Send a test mail now? [Y/n]: " T
    T=${T:-Y}
    [[ "$T" =~ ^[YyJj]$ ]] && send_test || pause
}

send_test() {
    is_setup || { echo "Not set up yet."; pause; return; }

    local from default_rcpt
    from=$(get_val from)
    default_rcpt=$(awk '/^root:/ {print $2}' "$ALIASES" 2>/dev/null || echo "$from")

    read -rp "Recipient [${default_rcpt}]: " RCPT
    RCPT=${RCPT:-$default_rcpt}
    while [[ -z "$RCPT" ]]; do read -rp "  -> required: " RCPT; done

    echo ">>> Sending a test mail to $RCPT ..."
    if printf 'Subject: Test mail from %s\nFrom: %s\nTo: %s\n\nSMTP sending works.\nHost: %s\nTime: %s\n' \
        "$(hostname -f 2>/dev/null || hostname)" "$from" "$RCPT" "$(hostname)" "$(date '+%F %T')" \
        | msmtp --read-envelope-from -- "$RCPT" 2>&1; then
        echo ">>> Handed over successfully."
    else
        echo "!!! Failed. Last log lines:"
        tail -n 10 "$LOGFILE" 2>/dev/null || true
    fi
    pause
}

show_config() {
    is_setup || { echo "Not set up."; pause; return; }
    echo "--- $MSMTPRC (password masked) ---"
    sed 's/^password .*/password       ********/' "$MSMTPRC"
    echo
    echo "--- root alias ---"
    grep '^root:' "$ALIASES" 2>/dev/null || echo "(not set)"
    echo
    echo "--- sendmail binary ---"
    ls -l /usr/sbin/sendmail 2>/dev/null || echo "(not present)"
    pause
}

show_log() {
    [[ -f "$LOGFILE" ]] || { echo "There is no log."; pause; return; }
    tail -n 40 "$LOGFILE"
    pause
}

uninstall() {
    echo ">>> Uninstall SMTP mailer"
    echo

    local cur_rcpt
    cur_rcpt=$(awk '/^root:/ {print $2}' "$ALIASES" 2>/dev/null || true)

    echo "The following will be removed:"
    [[ -f "$MSMTPRC" ]]  && echo "  - configuration $MSMTPRC (including the SMTP password)" || true
    [[ -n "$cur_rcpt" ]] && echo "  - root alias in $ALIASES  (root: $cur_rcpt)   [asked]" || true
    [[ -f "$LOGFILE" ]]  && echo "  - send log $LOGFILE                           [asked]" || true
    echo
    echo "The packages stay installed. To remove them manually:"
    echo "    apt purge msmtp msmtp-mta bsd-mailx"
    echo "  (that also removes /usr/sbin/sendmail - cron and system mail then fail silently)"
    echo

    confirm "Really remove?" || { echo "Cancelled."; pause; return; }

    make_backup mail-setup "$MSMTPRC" "$ALIASES" "$LOGFILE" || { pause; return; }

    rm -f "$MSMTPRC"

    if [[ -n "$cur_rcpt" ]] && confirm "Remove the root alias ($cur_rcpt) from $ALIASES?" Y; then
        sed -i '/^root:/d' "$ALIASES"
        command -v newaliases &>/dev/null && newaliases 2>/dev/null || true
    fi

    if [[ -f "$LOGFILE" ]] && confirm "Delete the send log $LOGFILE?"; then
        rm -f "$LOGFILE"
    fi

    echo
    echo "Removed. Without $MSMTPRC sending fails - services that use 'mail'"
    echo "(tcp-monitor, auto-update) then only write to their log."
    pause
}

main_menu() {
    while true; do
        clear
        echo "==========================================="
        echo " SMTP mailer (msmtp)"
        echo "==========================================="
        if is_setup; then
            echo "Status:   set up"
            echo "Server:   $(get_val host):$(get_val port)"
            echo "Sender:   $(get_val from)"
            echo "Recipient (root alias): $(awk '/^root:/ {print $2}' "$ALIASES" 2>/dev/null || echo '-')"
        else
            echo "Status: not set up"
        fi
        echo
        echo "1) Set up / edit parameters"
        echo "2) Send a test mail"
        echo "3) Show the configuration"
        echo "4) Show the send log"
        echo "5) Uninstall"
        echo "6) Quit"
        read -rp "Choice: " CH
        case "$CH" in
            1) configure ;;
            2) send_test ;;
            3) show_config ;;
            4) show_log ;;
            5) uninstall ;;
            6) exit 0 ;;
            *) sleep 1 ;;
        esac
    done
}

case "${1:-}" in
    --test)      send_test ;;
    --uninstall) uninstall ;;
    "")          is_setup || configure; main_menu ;;
    *)           echo "Usage: $0 [--test|--uninstall|--version]"; exit 1 ;;
esac
